name: Documentation Release
on:
  push: {branches: [main]}
  workflow_dispatch:
env: {GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"}
permissions:
  contents: write # needed to push the built docs to the gh-pages branch
jobs:
  docs-release:
    name: Documentation Release
    runs-on: ubuntu-latest
    steps:
      - {name: Checkout repo,          uses: actions/checkout@v5, with: {fetch-depth: 0}}
      - {name: Setup python,           uses: actions/setup-python@v6, with: {python-version: '3.x'}}
      - {name: Install dependencies,   run: "pip install -r make_requirements.txt"}
      - {name: Install adadmire,       run: "pip install ."}
      - {name: Build documentation,    run: "python make.py docs"}
      - {name: Upload to GitHub Pages, run: "python make.py docs_release"}
