name: GitHub Release
on:
  push: {branches: [main]}
  workflow_dispatch:
env: {GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"}
permissions:
  contents: write # needed to create the tag and the release
jobs:
  github-release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - {name: Checkout repo,  uses: actions/checkout@v5, with: {fetch-depth: 0}}
      - {name: Setup python,   uses: actions/setup-python@v6, with: {python-version: '3.x'}}
      - {name: Install deps,   run: "pip install -r make_requirements.txt"}
      - {name: Create Release, run: "python make.py gh_release"}
