# Based on: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
name: Tests
on: {push: {branches: [main, auto-release]}, pull_request: {branches: [main]}}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy: {matrix: {python-version: ['3.8', '3.12']}} # '3.9', '3.10', '3.11',
    steps:
      - {name: Checkout repo, uses: actions/checkout@v4}
      - {name: Install python, uses: actions/setup-python@v5, with: {python-version: "${{ matrix.python-version }}"}}
      - {name: Build adadmire, run: "python -m build"}
      - {name: Install adadmire, run: "python -m pip install ./dist/adadmire-*-py3-none-any.whl"}
      - {name: Import adadmire, run: "python -c 'import adadmire'"}
      - {name: Prepare tests, run: "pip install make_requirements.txt"}
      - {name: Check version, run: "pytest -k test_version"}
      - {name: Run test suite, run: "pytest --runslow"}
      - {name: Code coverage, uses: codecov/codecov-action@v2}