# Based on:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
name: Test Package
on:
  push:
    branches: [main, master, deps]
  pull_request:
    branches: [main, master, deps]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build requests packaging
      - name: Build package
        run: python -m build
      - name: Test install
        run: |
          python -m pip install ./dist/adadmire-*-py3-none-any.whl
      - name: Test import
        run: |
          python -c "import adadmire"
      - name: Check that version was incremented
        run: |
          current_version=$(grep 'version =' pyproject.toml | sed 's/version = "\(.*\)"/\1/' | tr -d " ")
          pypi_version=$(curl -s https://pypi.org/pypi/adadmire/json | python -c "import sys, json; print(json.load(sys.stdin)['info']['version'])")
          echo "Current version: $current_version"
          echo "PyPI version: $pypi_version"
          python -c "from packaging import version; import sys; sys.exit(0 if version.parse('$current_version') > version.parse('$pypi_version') else 1)"
