# Based on: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
name: Unit Tests
on: {push: {branches: [main]}, pull_request: {branches: [main]}}
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy: {matrix: {python-version: ['3.8', '3.12']}} # '3.9', '3.10', '3.11',
    steps:
      - {name: Checkout repo, uses: actions/checkout@v4}
      - {name: Install python, uses: actions/setup-python@v5, with: {python-version: "${{ matrix.python-version }}"}}
      - {name: Install dependencies, run: "pip install -r make_requirements.txt"}
      - {name: Build adadmire, run: "python -m build"}
      - {name: Install adadmire, run: "python -m pip install ./dist/*.whl"}
      - {name: Run pytest, run: "pytest --runslow -n 4"}
      - {name: Upload coverage, uses: codecov/codecov-action@v2}
